### ISSUE TITLE
Concern on the email addresses harvested for spam

### ISSUE THREAD

**Issue by am1ru1** [todogroup/governance#138]
From concerned external party, the email addresses inside [https://github.com/todogroup/governance/blob/master/MEMBERS.csv](url) seems like a solid target for spammer. Consider making it private, masking, hash it or image-tize it.

Example:
https://github.com/maldevel/EmailHarvester
https://www.atompark.com/web-email-extractor/free-email-lists/

**Comment by anajsana** [comment]
Hi, @am1ru1 thanks for sharing your concerns about this. We discussed this topic in the last TODO Work-Day call and the idea is to move the sensitive info (like emails) to this private repo: https://github.com/todogroup/administration/  where only the TODO Steering Committee can see and manage. In order to not confuse people, we decided to wait until the SC elections are finished.
