### ISSUE TITLE
Review Strategic goals 2022 by Steering Committee

### ISSUE THREAD

**Issue by anajsana** [todogroup/governance#160]
Proposed TODO Goals for 2022: https://github.com/todogroup/governance/blob/main/goals.md

## Tasks for the next SC Meeting

- [x] Decide the [goals](https://github.com/todogroup/governance/blob/main/goals.md#proposed-2022) where each SC member would like to help and work at. Please SC members use this [g.doc](https://docs.google.com/document/d/1dMzhXHfb_RP51nUkjQR6Fyg8jC1aZFYAcU3F1tx03uY/edit) and follow the instructions. The final version of the draft will be approved in the next SC meeting (April)

**Comment by anajsana** [comment]
Related to what @vmbrasseur commented about what was accomplished / not accomplished from the previous TODO SC Goals (2021) There is a blog article that summarizes the milestones achieved during the last year: https://todogroup.org/blog/a-year-in-review-2021/

Also, I shared with the 2021 SC an [Annual Report slide presentation](https://docs.google.com/presentation/d/1S6Ys9rui2IIhpLJMBbr0Qlr2Wezl6KYH2T9FXhc_VOk/edit?usp=sharing) that shows this in more detail + OSPO / TODO challenges and proposals for 2022 (e.g see slide 28)

**Comment by anajsana** [comment]
Adding the related comments discussed during  the last SC meeting:

@vmbrasseur suggests an issue for setting goals, create a PR w/these goals so we can comment, then work on it async & approve at next call. 

@itprofjacobs discusses past experience with IDGA where a group ended up splitting up because the group was spending so much time helping folks new to the topic that experienced folks felt it wasn’t a place for them. They split off.

@tsteenbe agrees, that they see this in the EU group. < 2-3yr group talks about different things than 3-10yr group, for instance.

@anajsana notes that we don’t get a lot of respondents for the TODO Group survey, so we don’t have a lot of data.

@ashleywolf suggests a working group to review different lifecycle segments of OSPOs & whether we have content/a forum for them.

@itprofjacobs  suggests that we create content to engage the #general members to try to convert them the Real Members. OSPOlogy is a start.

**Comment by vmbrasseur** [comment]
I've created a PR (#163) for the goals.md doc so we can make comments at a line level, iterate on the goals, and merge them once they're approved by the SC.

**Comment by vmbrasseur** [comment]
FYI, I'm going to put my questions/discussion over on that PR.

**Comment by anajsana** [comment]
> FYI, I'm going to put my questions/discussion over on that PR.

Just added my comments there too 👍

**Comment by anajsana** [comment]
I've opened a PR to @vmbrasseur PR that changes SC structure to make a clear division between SC and LF Staff goals: https://github.com/todogroup/governance/pull/179

Please feel free to make any changes to the content 👍

**Comment by chrisxie-fw** [comment]
In terms of TODO Group's strategic goals, in addition to the Open Source Mgmt and Operation side of things that TODO Group already issued guides on, I would suggest to include some strategic verticals (such as Climate Tech) and horizontals (such as Open Source Sustainability & Security) topics by facilitating a mechanism to gauge community interest of certain topics (maybe in the form of a survey), and creating a mechanism to form Special Interest Groups within TODO.

**Comment by anajsana** [comment]
Thanks for taking a look at the goals and providing feedback and ideas to them @chrisxie-fw ! 🙏 As you can see, the SC committee agreed on the [high-level goals](https://github.com/todogroup/governance/blob/main/goals.md#proposed-2022), but we have to iterate on each of them to go into more detail about what specific actions needs to be accomplished.

In order to better frame your request, I think that what you proposed is something that should be discussed as a potential action item related to the ["Cultivate relationships with other communities"](https://github.com/todogroup/governance/blob/main/goals.md#%EF%B8%8F-grow-the-community) goal. Here comes my reasoning for this:

⬇️⬇️⬇️

Indeed, there are vertical topics discussed at TODO. Many times, those topics were already covered by other specialized open source communities (e.g LF Energy, CHAOSS for open source metrics and project sustainability standards, LF Health for open source in the healthcare industry, FINOS for open source in the financial sector, OpenChain for open source security and licensing standarts, InnerSource Commons for innersource standards and patterns, etc).

The challenge I see is HOW to file those TODO community needs to the specific specialized communities and collaborate and Sync with them to: 

(1) Drive awareness and share existing resources with the TODO community in order to don't duplicate efforts and vice versa 

(2) Build new resources that don't exist that benefit both ecosystems (e.g building micro-surveys about OSPOs in the finance sector collaborating with FINOS, or OSPO sustainability metrics collaborating with CHAOSS).

**Comment by vmbrasseur** [comment]
Thanks for all your work on this, @anajsana!

What's the next step for moving this issue forward?

**Comment by anajsana** [comment]
@vmbrasseur: SC should iterate on each of the [Strategic Goals](https://github.com/todogroup/governance/blob/main/goals.md#proposed-2022) that need further details/guidance and provide a more detailed description of what is expected to be accomplished for those goals. 

For instance, what actions are expected to achieve the goal of "Cultivate relationships with other communities"?. I made a suggestion on the previous comment: https://github.com/todogroup/governance/issues/160#issuecomment-1034885921

I would suggest opening a new PR that adds changes to the `.md`file to extend the SC goal's description and specific actions 👍 Then, reserve some time during the SC meeting to review and approve/decline/change.

**Comment by chrisxie-fw** [comment]
I would suggest the Todo Group goals be categorized as operational goals, and strategic goals. 

*Strategic goals* refer to those that may have huge potential *industry-wide impacts*. One example is *Open Source Sustainability and Security*. Yes, there are other organizations specifically focused on that subject, but the recent sustainability and security incidents suggest that it takes a (global) village to address the challenge of a *systematic nature*. It needs to be addressed in a holistic manner while patches here and there. 

Todo Group as a *Central* OSS org is supposedly uniquely well-positioned to take the lead on this challenge to help:
- define the  problem statement
- identify the root cause, and  
- make recommendations and best practices/suggestions to the industry, in collaboration with other global communities. 

Specific actions for ToDo Group could be to start with a survey, to identify those who are interested in participating in this Special Interest Group (SIG). There appears to be 1568 members in the [Todo Slack channel](https://app.slack.com/client/T0GC1DABT/C0GBYUWCB). So the survey could be casted in that bigger group. If there is enough interest, an SIG can be formed. The SIG then determines what specific goals to achieve, and the initial goals can start with baby steps, with a vision, to:
- engage with other orgs 
- create industry guides/white papers
- make suggestions to create globally neutral industry organizations to fund/sustain (foundational/critical) open source projects and security maintenance, ethical and climate-aware development, and other cross-cutting concerns, standards and tools etc.
- create open source sustainability index/benchmark. An example of such a benchmark organization in the ML area is [MLCommons (MLPerf)](https://mlcommons.org/en/). 
- ...

Here I'm helping ToDo Group to formulate/crystalize a process/mechanism with a concrete example to create subworking groups (e.g. SIG), and maybe SC's role is to determine if this is reasonable and approve such a process, and community manager can then implement such processes to establish SIG's that:
- foster further community engagement
- create more value to the community and the industry at large. 

With this specific example, the goals of ToDo Group, LF Staff, and the Community may be much clearer. Hope this helps.

**Comment by anajsana** [comment]
## Tasks for the next SC Meeting

- [ ] Decide the [goals](https://github.com/todogroup/governance/blob/main/goals.md#proposed-2022) where each SC member would like to help and work at. Please SC members use this [g.doc](https://docs.google.com/document/d/1dMzhXHfb_RP51nUkjQR6Fyg8jC1aZFYAcU3F1tx03uY/edit) and follow the instructions. The final version of the draft will be approved in the next SC meeting (April)

**Comment by anajsana** [comment]
@todogroup/steering-committee added [a description](https://docs.google.com/document/d/1dMzhXHfb_RP51nUkjQR6Fyg8jC1aZFYAcU3F1tx03uY/edit#heading=h.4r9xh3j9ps4u) within the "Cultivate relationships with other communities" goal. Anyone interested to help with this topic, review and add your comments 👍

**Comment by anajsana** [comment]
Milestones according to the approved strategic goals and assigned issues for the different milestones have been created: https://github.com/todogroup/governance/milestones

Closing this issue so SC members can work on the different issues generated. Thanks a lot for taking the time to work on this! 💯 👍
