### ISSUE TITLE
branch protection rules

### ISSUE THREAD

**Issue by gyehuda** [todogroup/governance#69]
Should we set up branch protection on some of our repos to ensure that more than one pair of eyes is involved in a change to content? If so, which? If not, at least we raised the conversation and decided.

**Comment by vmbrasseur** [comment]
I'm on the fence.

On the one hand, we're not really target material. This would be premature optimisation and add overhead.

On the other hand…it's not like it's a lot of overhead and I don't anticipate it'd be that onerous or otherwise slow us down.

**Comment by willnorris** [comment]
+1 to @vmbrasseur's comment.  I'd suggest we try it and see if it really turns out to be too much overhead?

**Comment by justaugustus** [comment]
Sub-item of https://github.com/todogroup/governance/issues/106.

**Comment by anajsana** [comment]
@justaugustus can we close this? I think it's done now that the SC has admin access to the whole GH org, so more than one person have the right permissions to change content

**Comment by anajsana** [comment]
branch protection rules are enabled in the most active repos, including:

ospology 
todogorup.org
ospo-career-path

Since this is a very old issue, I will close this and suggest opening a new issue if needed to work on defining a concrete branch protection rule (e.g approval from a second reviewer required) in a targeted repo (e.g ospolandscape) in the future 👍
